server.port: 8085
spring:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/pizza_shop?serverTimezone=UTC
    username: pizza_shop
    password: pizza_shop